travis:
  secure:
    BINSTAR_TOKEN: IZpQTtCA3yUVOrFqmt+3sdowsPdyWrbB/816NgndaFlbdWsFjMtNk9nYyM3uCVoIyCjGSAmtkCpC8cCxV3OpyCvnZSveQHnF8j+P0DxyF0FSjz/W/BbbLgydh069u2+pYMMk1zDIoyekuDzQglQR366ASoMSDnAIX8jDUzlQR+aN9G6nH/tCQ1cNyJobFgDUIZTCtDgxYer2IdSB1do0hn2svLOWZS/rpdKsX6CFgD1YQbQKrNadJCNPqD7t2Wwe9poVO6qWGNXH2+1mN9gJkBm3XiALN0aHpCtjXsMagfQzf2hh8dzyNxbaBNV7ITRWx1OvrNlC6uP0biRnBFntod+TXh9trs1f2gTk8kPdH8P6FuFdktVNKfIcAVc7IMdZDmbiMMNNA8Xzp6SB2jW+Lmy8NRWn45ms38tHZ11GgMX0hMphoP8Gfef03DxRFcgqAFjLz0Rfc8WEZcoL17+OuvVNgnTlFClGLRKqVnawHj46YPJ6AV/tFno+Q0T3Zd93ret093VaLFRJZ7DjNKQ9HjCSJ5FEl99qd0hVNKzMQ1SxQPCzU6hSzZEiAwyijKaJzBV18gjR17LiVStvRfnr2Dtt3lGjEwRysC/2N8TmLPxJegm9U5Lf97wXcI5OqsSe7Ol7Z2BOcohVOVKYaqrxtcpEz9hXpeLWKYQ4nq+MsEs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
